### ISSUE TITLE
Want to add my information in intrested-technical-writers.md

### ISSUE THREAD

**Issue by manastole03** [google/season-of-docs#117]
Hello everyone, I am Manas Tole. 
I want to add my social information in this repository.

Thank you :)

**Comment by emckean** [comment]
Hi Manas! To add your information to the list of [interested technical writers](https://github.com/google/season-of-docs/blob/main/2021-participants/interested-technical-writers.md), please [make a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

**Comment by emckean** [comment]
Closing this issue as no response for >3 weeks
