### ISSUE TITLE
"Next steps" message in GSoD submission form lists incorrect dates

### ISSUE THREAD

**Issue by fkiraly** [google/season-of-docs#1371]
The "next steps" message (shown after submission) in the submission form lists incorrect dates, likely the 2022 dates:

![image](https://github.com/google/season-of-docs/assets/7985502/cbc910eb-bdf0-40d2-95d8-de1488a3c4fc)

**Comment by emckean** [comment]
Thank you very much for reporting this! Updated now. :)

**Comment by fkiraly** [comment]
Thanks. Glad to have implicit confirmation that we aren't 2 years late.
