### ISSUE TITLE
ExpressLRS accidentally removed  from the list of participating organizations

### ISSUE THREAD

**Issue by wallrj** [google/season-of-docs#503]
@xmulligan and @rominaminav You accidentally removed ExpressLRS from the list (added by @JyeSmith in #486).

_Originally posted by @wallrj in https://github.com/google/season-of-docs/pull/487#discussion_r837242113_

**Comment by JyeSmith** [comment]
Thanks for catching this @wallrj  👍

**Comment by xmulligan** [comment]
Thanks, it looks like it is because of the order they were merged in. I've created a PR to fix it here https://github.com/google/season-of-docs/pull/504
