### ISSUE TITLE
remote rejected: push declined due to email privacy restrictions

### ISSUE THREAD

**Issue by yokwejuste** [google/season-of-docs#640]
## Description:
Don't know if this is from side but an issue when I was trying to push the edits to GitHub. The push denied.

I'll like to know more about that please.
## Screenshot
![Screenshot from 2023-01-19 06-43-58](https://user-images.githubusercontent.com/71908316/213368055-985e8a87-7687-48a9-afa8-c0cefc702cfc.png)

**Comment by StanleyMasinde** [comment]
Hi @yokwejuste, that's not a bug it's a Github feature.
You've set your email to private and Github is doing what your settings want it to do - protect your email.

You can either 
1. `git config --local user.email <a public email>`
2. Go to <https://github.com/settings/emails> to make your commit email public.

Happy coding

**Comment by yokwejuste** [comment]
Thanks for this highlight
