### ISSUE TITLE
The Readme For participants should specify the agreement

### ISSUE THREAD

**Issue by unworld11** [google/season-of-docs#682]
if we mention it in the readme it will help resolving so many errors the first timers are getting while raising pull requests.

**Comment by unworld11** [comment]
Please assign this issue to me

**Comment by emckean** [comment]
Hi! Good idea, added link now

**Comment by unworld11** [comment]
can you add me as a contributor?

**Comment by emckean** [comment]
Hi, unfortunately no. We appreciate the suggestion though!
