### ISSUE TITLE
Contributing to Google Season Of Docs

### ISSUE THREAD

**Issue by Ajay-singh1** [google/season-of-docs#773]
Hi There!I want to contribute to Google Season of Docs How can I contribute to it?
I am interested in technical writing and also had written some technical guide for some projects.

**Comment by emckean** [comment]
Hi! Please read the [Guide for Technical Writers](https://developers.google.com/season-of-docs/docs/tech-writer-guide).

**Comment by Ajay-singh1** [comment]
Thanks!
