### ISSUE TITLE
Table format issue for 2023 participants file

### ISSUE THREAD

**Issue by sunkanmii** [google/season-of-docs#883]
The table format in the "https://github.com/google/season-of-docs/blob/main/2023-participants/interested-technical-writers.md" file from the name "Utibo Etim" down to "Olasunkanmi Fafowora" (mine) doesn't display correctly on the table.

![Screenshot of table format error)](https://user-images.githubusercontent.com/29275879/220778513-e4ceea10-c1e5-4ac9-949f-d01fd60b48bc.png)

**Comment by emckean** [comment]
Thank you! should be fixed now.
